export enum States {
  BUENOS_AIRES = "buenos_aires",
  CATAMARCA = "catamarca",
  CHACO = "chaco",
  CHUBUT = "chubut",
  CORDOBA = "cordoba",
  CORRIENTES = "corrientes",
  ENTRE_RIOS = "entre_rios",
  FORMOSA = "formosa",
  JUJUY = "jujuy",
  LA_PAMPA = "la_pampa",
  LA_RIOJA = "la_rioja",
  MENDOZA = "mendoza",
  MISIONES = "misiones",
  NEUQUEN = "neuquen",
  RIO_NEGRO = "rio_negro",
  SALTA = "salta",
  SAN_JUAN = "san_juan",
  SAN_LUIS = "san_luis",
  SANTA_CRUZ = "santa_cruz",
  SANTA_FE = "santa_fe",
  SANTIAGO_DEL_ESTERO = "santiago_del_estero",
  TIERRA_DEL_FUEGO = "tierra_del_fuego",
  TUCUMAN = "tucuman",
}
